1.0.15 proper error handling for db calls and encrypted passwords * [x] 1.0.15 - frontend/api: translation being impossible for some reason, we now only fw the backend messages * [x] 1.0.15 - frontend/api: impossible to add translation because TypeError: react_i18next__WEBPACK_IMPORTED_MODULE_2__["default"] is not a function * [x] 1.0.15 - frontend.js: impossible to add translation to logger because Invalid hook call * [x] 1.0.15 - common.js now only contains portable functions * [x] 1.0.15 - backend: YET AGAIN... js refuses to offer a caller id stack == custom logger with stack hack * [x] 1.0.15 - had to REdevelop logger() with colors, YET AGAIN * [x] 1.0.15 - backend/db: init the db on start * [x] 1.0.15 - backend/db: automated patch upgrade of db * [x] 1.0.15 - backend/db: proper error handling for dbOpen, dbRun, dbGet, dbAll, dbInit, dbUpdate * [x] 1.0.15 - backend/env: handle versions with a "v" and keep only the numbers * [x] 1.0.15 - frontend/Settings/logins: test getLogins, saveLogins * [x] 1.0.15 - frontend/Settings/logins: do not bring password back in as they are salted 	modified:   CONTRIBUTING.md 	modified:   Dockerfile 	modified:   backend/accounts.js 	modified:   backend/aliases.js 	modified:   backend/db.js 	modified:   backend/env.js 	modified:   backend/index.js 	modified:   backend/logins.js 	modified:   backend/settings.js 	modified:   common/backend.js 	modified:   common/frontend.js 	modified:   frontend/src/components/DashboardCard.js 	modified:   frontend/src/locales/en/translation.json 	modified:   frontend/src/pages/Accounts.js 	modified:   frontend/src/pages/Aliases.js 	modified:   frontend/src/pages/Dashboard.js 	modified:   frontend/src/pages/FormLogins.jsx 	modified:   frontend/src/pages/FormSettings.jsx 	modified:   frontend/src/pages/ServerInfos.jsx 	modified:   frontend/src/pages/Settings.js 	modified:   frontend/src/services/api.js