v1.1.0 login page! * [x] 1.0.20 - backend/settings: numbers from pullServerEnv are saved as float in the db: CAST(@value AS TEXT) does not work, obj2ArrayOfObj now can stringify values * [x] 1.0.20 - backend/settings: pullServerEnv and saveServerEnvs take containerName as parameter * [x] 1.0.20 - backend: fix in logger when appending end color * [x] 1.0.20 - Dashboard does not show container usage anymore: resources{} names have changed somehow; defered cpu/mem conversion to Dashboard * [x] 1.0.19 - loginPage and loginUser implemented! * [x] 1.0.19 - logout button in NavBar * [x] 1.0.19 - frontend/App: add auth loginPage * [x] 1.0.18 - ALL WORKS, we should release * [x] 1.0.18 - backend/db: dbRun now takes anonParam as well as arrays for INSERT queries * [x] 1.0.18 - backend: added getSetting and updated getSettings api with query * [x] 1.0.18 - frontend: fixed Accounts.js and ServerInfos.jsx to use new getServerInfos and getServerEnvs * [x] 1.0.18 - backend/api: getServerInfos is simplified and created getServerEnvs * [x] 1.0.17 - backend: added sql for infos: it's in settings table with scope = DMS name * [x] 1.0.17 - backend: added sql for infos * [x] 1.0.17 - backend/api: getSettings/saveSettings uses json array of objects * [x] 1.0.17 - backend/db: patches are array of lines instead of BEGIN TRANSACTION so we can check each line * [x] 1.0.17 - backend: added 2 columns to settings and merged with infos * [x] 1.0.17 - backend: moved internals DB_VERSION_table to settings * [x] 1.0.16 - frontend/Card: Placeholder Card to be created once we need it * [x] 1.0.16 - frontend/Card: Extra spinner when isLoading in titleExtra * [x] 1.0.16 - frontend/Dashboard: DashboardCards load individually * [x] 1.0.15 - frontend/api: translation being impossible for some reason, we now only fw the backend messages * [x] 1.0.15 - frontend/api: impossible to add translation because TypeError: react_i18next__WEBPACK_IMPORTED_MODULE_2__["default"] is not a function * [x] 1.0.15 - frontend.js: impossible to add translation to logger because Invalid hook call * [x] 1.0.15 - common.js now only contains portable functions * [x] 1.0.15 - backend: YET AGAIN... js refuses to offer a caller id stack == custom logger with stack hack * [x] 1.0.15 - had to REdevelop logger() with colors, YET AGAIN * [x] 1.0.15 - backend/db: init the db on start * [x] 1.0.15 - backend/db: automated patch upgrade of db * [x] 1.0.15 - backend/db: proper error handling for dbOpen, dbRun, dbGet, dbAll, dbInit, dbUpdate * [x] 1.0.15 - backend/env: handle versions with a "v" and keep only the numbers * [x] 1.0.15 - frontend/Settings/logins: test getLogins, saveLogins * [x] 1.0.15 - frontend/Settings/logins: do not bring password back in as they are salted * [x] 1.0.14 - backend/logins: encrypt password in db.logins.json * [x] 1.0.14 - frontend/Button: add a link to parameters * [x] 1.0.14 - frontend/Settings/logins: test getLogins * [x] 1.0.14 - frontend/Settings: now an Accordion as we will have to deal with many parts * [x] 1.0.14 - frontend/pages: bugfix with booleans passed to components * [x] 1.0.13 - moved all env global variables into env.js * [x] 1.0.13 - split all common functions into /app/common/backend.js and frontend.js * [x] 1.0.13 - backend/logins: implemented dbGet, dbAll, dbRun, save, get, verifyPassword, hashPassword * [x] 1.0.13 - backend: implemented better-sqlite3 and sql for settings and logins * [x] 1.0.13 - Dockerfile: switched all base images to node:24-alpine as slim is incompatible with better-sqlite3 * [x] 1.0.13 - backend: implement sqlite3; wasted 20mn of my life, moving on. * [x] 1.0.12 - frontend/Sidebar: .leftsidebar inline-flex is the solution for collapse but then impossible to place the button properly * [x] 1.0.12 - frontend/Aliases: add LeftSidebar collapse button * [x] 1.0.12 - frontend/Aliases: renamed Sidebar to LeftSidebar * [x] 1.0.11 - frontend/CardFormSettings: pops an error saying A component is changing an uncontrolled input to be controlled: fixed by testing data properly when isLoading * [x] 1.0.11 - backend/getSmth: bugfix yet again when db is empty or missing data: no refresh would ever take place * [x] 1.0.11 - frontend/Accounts: add refresh icon to Accordion * [x] 1.0.10 - BUG: since sorting and filtering is added, change highlighting does not happen anymore * [x] 1.0.10 - BUG: find a way to hide the arrows for object columns with no data * [x] 1.0.10 - frontend/DataTable: handle filtering for rendered object columns like we do for sorting * [x] 1.0.10 - frontend/DataTable: add column filtering to DataTable: complete rewrite of DataTable with proper use of useRef and useMemo * [x] 1.0.9 - back to ubuntu-latest worker in update-dockerhub.yml